=== pczajor/WBA2-Phase-2/WBA2-Phase2/src/xsd/orte.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Orteliste" type="OrteType" />
	

	<xs:complexType name="OrteType">
		<xs:sequence>
			<xs:element name="Ort" type="oType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="oType">
		<xs:sequence>
			<xs:element name="Ort" type="xs:string" />
			<xs:element name="Platz" type="xs:string" />
			<xs:element name="min.Spieleranzahl" type="xs:positiveInteger" />
			<xs:element name="max.Spieleranzahl" type="xs:positiveInteger" />
			<xs:element name="Oeffnungszeiten">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="geoeffnet_von" type="xs:time" />
						<xs:element name="geoeffnet_bis" type="xs:time" />
						<xs:element name="geschlossen_an" type="xs:string" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Preis">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="0" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


</xs:schema>

=== pczajor/WBA2-Phase-2/WBA2-Phase2/src/xsd/orte.xml
<?xml version="1.0" encoding="UTF-8"?>
<Orteliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="orte.xsd">
  <Ort>
    <Ort>Ort</Ort>
    <Platz>Platz</Platz>
    <min.Spieleranzahl>1</min.Spieleranzahl>
    <max.Spieleranzahl>1</max.Spieleranzahl>
    <Oeffnungszeiten>
      <geoeffnet_von>12:00:00</geoeffnet_von>
      <geoeffnet_bis>12:00:00</geoeffnet_bis>
      <geschlossen_an>geschlossen_an</geschlossen_an>
    </Oeffnungszeiten>
    <Preis>0.0</Preis>
  </Ort>
</Orteliste>
