=== pczajor/WBA2-Phase-2/WBA2-Phase2/bin/xsd/accounts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Accountliste" type="slType" />
	

	<xs:complexType name="slType">
		<xs:sequence>
			<xs:element name="Spieler" type="spielerType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="spielerType">
		<xs:sequence>
			<xs:element name="Anzeigename" type="xs:string" />
			<xs:element name="Telefonnummer" type="xs:string" />
		</xs:sequence>
	</xs:complexType>


</xs:schema>

=== pczajor/WBA2-Phase-2/WBA2-Phase2/bin/xsd/accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<Accountliste xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="accounts.xsd">
  <Spieler>
    <Anzeigename>Michael</Anzeigename>
    <Telefonnummer>01234</Telefonnummer>
  </Spieler>
  
  <Spieler>
    <Anzeigename>Hans</Anzeigename>
    <Telefonnummer>012345</Telefonnummer>
  </Spieler>
  
  <Spieler>
    <Anzeigename>Klaus</Anzeigename>
    <Telefonnummer>0123456</Telefonnummer>
  </Spieler>
  
  <Spieler>
    <Anzeigename>Michael</Anzeigename>
    <Telefonnummer>8910</Telefonnummer>
  </Spieler>
  
  <Spieler>
    <Anzeigename>Frank</Anzeigename>
    <Telefonnummer>125</Telefonnummer>
  </Spieler>
  
  <Spieler>
    <Anzeigename>Monika</Anzeigename>
    <Telefonnummer>123</Telefonnummer>
  </Spieler>
  
  <Spieler>
    <Anzeigename>Torsten</Anzeigename>
    <Telefonnummer>017234</Telefonnummer>
  </Spieler>
  
  <Spieler>
    <Anzeigename>Ben</Anzeigename>
    <Telefonnummer>012334</Telefonnummer>
  </Spieler>
</Accountliste>
