=== pczajor/WBA2-Phase-2/WBA2-Phase2/bin/xsd/event.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


	<xs:element name="Events">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="event" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Event-ID" type="xs:positiveInteger" />
							<xs:element name="Spielzeitraum">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="von" type="xs:dateTime" />
										<xs:element name="bis" type="xs:dateTime" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Sportart">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="FuÃŸball" />
										<xs:enumeration value="Basketball" />
										<xs:enumeration value="Tennis" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Oertlichkeit">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Ort-ID" type="xs:positiveInteger" />
										<xs:element name="Ort" type="xs:string" />
										<xs:element name="Platz" type="xs:string" />
										<xs:element name="min.Spieleranzahl" type="xs:positiveInteger" />
										<xs:element name="max.Spieleranzahl" type="xs:positiveInteger" />
										<xs:element name="Oeffnungszeiten">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="geoeffnet_von" type="xs:time" />
													<xs:element name="geoeffnet_bis" type="xs:time" />
													<xs:element name="geschlossen_an" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Preis">
											<xs:simpleType>
												<xs:restriction base="xs:decimal">
													<xs:minInclusive value="0" />
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Spielerliste">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Spieler" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Anzeigename" type="xs:string" />
													<xs:element name="Telefonnummer" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="subAdmin" type="xs:boolean" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="min.Spieler" type="xs:positiveInteger" />
									<xs:attribute name="max.Spieler" type="xs:positiveInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="Backlist">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Spieler" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Anzeigename" type="xs:string" />
													<xs:element name="Telefonnummer" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="subAdmin" type="xs:boolean" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Admin">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Anzeigename" type="xs:string" />
										<xs:element name="Telefonnummer" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="subAdmin" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>



</xs:schema>

=== pczajor/WBA2-Phase-2/WBA2-Phase2/src/xsd/event.xml
<?xml version="1.0" encoding="UTF-8"?>
<Events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="event.xsd">
  <event>
    <Spielzeitraum>
      <von>2001-12-31T12:00:00</von>
      <bis>2001-12-31T12:00:00</bis>
    </Spielzeitraum>
    <Sportart>Fu√üball</Sportart>
    <Oertlichkeit>
      <Ort>Ort</Ort>
      <Platz>Platz</Platz>
      <min.Spieleranzahl>1</min.Spieleranzahl>
      <max.Spieleranzahl>1</max.Spieleranzahl>
      <Oeffnungszeiten>
        <geoeffnet_von>12:00:00</geoeffnet_von>
        <geoeffnet_bis>12:00:00</geoeffnet_bis>
        <geschlossen_an>geschlossen_an</geschlossen_an>
      </Oeffnungszeiten>
      <Preis>0.0</Preis>
    </Oertlichkeit>
    <Spielerliste>
      <Spieler>
        <Anzeigename>Anzeigename</Anzeigename>
        <Telefonnummer>Telefonnummer</Telefonnummer>
      </Spieler>
    </Spielerliste>
    <Backlist>
      <Spieler>
        <Anzeigename>Anzeigename</Anzeigename>
        <Telefonnummer>Telefonnummer</Telefonnummer>
      </Spieler>
    </Backlist>
    <Admin>
      <Anzeigename>Anzeigename</Anzeigename>
      <Telefonnummer>Telefonnummer</Telefonnummer>
    </Admin>
  </event>
</Events>

=== pczajor/WBA2-Phase-2/WBA2-Phase2/bin/xsd/event.xml
<?xml version="1.0" encoding="UTF-8"?>
<Events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="event.xsd">
	<event>
		<Event-ID>1</Event-ID>
		<Spielzeitraum>
			<von>2013-07-31T12:00:00</von>
			<bis>2013-07-31T14:00:00</bis>
		</Spielzeitraum>
		<Sportart>Fußball</Sportart>
		<Oertlichkeit>
			<Ort-ID>2</Ort-ID>
			<Ort>Gummersbach</Ort>
			<Platz>Eugen-Haas Sporthalle</Platz>
			<min.Spieleranzahl>10</min.Spieleranzahl>
			<max.Spieleranzahl>40</max.Spieleranzahl>
			<Oeffnungszeiten>
				<geoeffnet_von>10:00:00</geoeffnet_von>
				<geoeffnet_bis>20:30:00</geoeffnet_bis>
				<geschlossen_an>Sonntag</geschlossen_an>
			</Oeffnungszeiten>
			<Preis>5</Preis>
		</Oertlichkeit>
		<Spielerliste>
			<Spieler subAdmin=true>
				<Anzeigename>Hans</Anzeigename>
				<Telefonnummer>012345</Telefonnummer>
			</Spieler>

			<Spieler>
				<Anzeigename>Klaus</Anzeigename>
				<Telefonnummer>0123456</Telefonnummer>
			</Spieler>
		</Spielerliste>
		<Backlist>
			<Spieler>
				<Anzeigename>Michael</Anzeigename>
				<Telefonnummer>8910</Telefonnummer>
			</Spieler>

			<Spieler>
				<Anzeigename>Frank</Anzeigename>
				<Telefonnummer>125</Telefonnummer>
			</Spieler>
		</Backlist>
		<Admin>
			<Anzeigename>Ben</Anzeigename>
			<Telefonnummer>012334</Telefonnummer>
		</Admin>
	</event>

	<event>
		<Event-ID>2</Event-ID>
		<Spielzeitraum>
			<von>2013-07-29T12:00:00</von>
			<bis>2013-07-29T14:00:00</bis>
		</Spielzeitraum>
		<Sportart>Fußball</Sportart>
		<Oertlichkeit>
			<Ort-ID>3</Ort-ID>
			<Ort>Köln</Ort>
			<Platz>Rheinenergie-Stadion</Platz>
			<min.Spieleranzahl>5</min.Spieleranzahl>
			<max.Spieleranzahl>22</max.Spieleranzahl>
			<Oeffnungszeiten>
				<geoeffnet_von>12:00:00</geoeffnet_von>
				<geoeffnet_bis>22:00:00</geoeffnet_bis>
				<geschlossen_an>Sonntag</geschlossen_an>
			</Oeffnungszeiten>
			<Preis>100000</Preis>
		</Oertlichkeit>
		<Spielerliste>
			<Spieler subAdmin=true>
				<Anzeigename>Hans</Anzeigename>
				<Telefonnummer>012345</Telefonnummer>
			</Spieler>

			<Spieler>
				<Anzeigename>Klaus</Anzeigename>
				<Telefonnummer>0123456</Telefonnummer>
			</Spieler>
		</Spielerliste>
		<Backlist>
			<Spieler>
				<Anzeigename>Michael</Anzeigename>
				<Telefonnummer>8910</Telefonnummer>
			</Spieler>

			<Spieler>
				<Anzeigename>Frank</Anzeigename>
				<Telefonnummer>125</Telefonnummer>
			</Spieler>
		</Backlist>
		<Admin>
			<Anzeigename>Ben</Anzeigename>
			<Telefonnummer>012334</Telefonnummer>
		</Admin>
	</event>
</Events>
